command_timeout   = 3000

format = """
$status $all $fill $git_branch$git_commit$git_state$git_metrics$git_status
$shell$character"""

[fill]
disabled = false
symbol = ' '

[character]
disabled = false
success_symbol = ' [ï”](bold green)'
error_symbol = ' [ï”](bold red)'

[status]
disabled = false
symbol = 'ğŸ¤¯'
success_symbol = 'ğŸ™‚'
not_found_symbol = 'ğŸ§'
sigint_symbol = 'ğŸ« '
not_executable_symbol = 'ğŸ¤'
format = '$symbol'
map_symbol = true

[directory]
truncation_length = 10
truncate_to_repo  = false

[aws]
disabled = true

[line_break]
disabled = true
