command_timeout   = 3000

format = """
$status $all
$shell$character """
right_format = """$git"""

[character]
disabled = false
success_symbol = '[ï”](bold green)'
error_symbol = '[ï”](bold red)'

[status]
disabled = false
symbol = 'ğŸ¤¯'
success_symbol = 'ğŸ™‚'
format = '$symbol'
map_symbol = true

[directory]
truncation_length = 10
truncate_to_repo  = false

[aws]
disabled = true

[line_break]
disabled = true
